#!/usr/bin/env bash
# Install the ai-usage helper and the Plasma widget.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bin_dir="${HOME}/.local/bin"
helper="${bin_dir}/ai-usage"
applet_id="com.nicl9923.aiusage"

restart_plasma=false
for arg in "$@"; do
  case "$arg" in
    --restart-plasma) restart_plasma=true ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

command -v kpackagetool6 >/dev/null || { echo "kpackagetool6 not found (install plasma-workspace)" >&2; exit 1; }

echo "==> Installing helper to ${helper}"
mkdir -p "$bin_dir"
cat > "$helper" <<EOF
#!/usr/bin/env bash
# Generated by ai-usage-widget scripts/install.sh
exec env PYTHONPATH="${repo_root}/src\${PYTHONPATH:+:\$PYTHONPATH}" python3 -m ai_usage "\$@"
EOF
chmod +x "$helper"

echo "==> Verifying helper"
"$helper" --plain >/dev/null || echo "    (helper ran but reported no usage; check that you are signed in)"

echo "==> Installing plasmoid"
if kpackagetool6 -t Plasma/Applet -l 2>/dev/null | grep -qx "$applet_id"; then
  kpackagetool6 -t Plasma/Applet -u "${repo_root}/plasmoid"
else
  kpackagetool6 -t Plasma/Applet -i "${repo_root}/plasmoid"
fi

if [ "$restart_plasma" = true ]; then
  echo "==> Restarting plasmashell"
  systemctl --user restart plasma-plasmashell.service
else
  echo
  echo "Add the widget from: Right-click panel > Add Widgets > 'AI Usage'"
  echo "If it does not appear, restart the shell:"
  echo "  systemctl --user restart plasma-plasmashell.service"
fi
